name: PrivateChest_pmmp
version: 1.0.0
main: KukukuWan\PrivateChest
api: 5.0.0
author: KukukuWan
description: PMMP用のチェストのロック・共有を管理するプラグイン
commands:
  pcc:
    description: PrivateChestのコマンド群
    usage: /pcc <lock|unlock|share|help>
    permission: privatechest.command
permissions:
  privatechest.command:
    description: PrivateChestコマンドを使用するための権限
    default: true
